server:
  port: 8082
  servlet:
    context-path: /reservaService

spring:
  application:
    name: reservaService
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/reserva?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

crud:
  rabbitmq:
    exchange: crud.exchange
    queueQuarto: crud.reserva.quarto
    queueUsuario: crud.reserva.usuario
    queueHotel: crud.reserva.hotel

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka
