server:
  port: 8084
  servlet:
    context-path: /consumoService

spring:
  application:
    name: consumoService
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/consumo?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

crud:
  rabbitmq:
    exchange: crud.exchange
    queueUsuario: crud.consumo.usuario
    queueProduto: crud.consumo.produto

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka

