
server:
  port: 8085
  servlet:
    context-path: /servicosService

spring:
  application:
    name: servicoService
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/servicos?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

crud:
  rabbitmq:
    exchange: crud.exchange
    queueUsuario: crud.servico.usuario
    queueServico: crud.servico.servico
    queueHotel: crud.servico.hotel

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka

